// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEmH4kvdk9gC0YawUiJYZBSHCN1joZmlw',
    appId: '1:831897287544:web:faa7f4a5d2eaee3b7fe68d',
    messagingSenderId: '831897287544',
    projectId: 'fitfam-c61fb',
    authDomain: 'fitfam-c61fb.firebaseapp.com',
    storageBucket: 'fitfam-c61fb.firebasestorage.app',
    measurementId: 'G-X1NV3D3N4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbzPAnIXLlmkAzdF3xANLkzJ7B7lr4aL0',
    appId: '1:831897287544:android:1a20fedd003520907fe68d',
    messagingSenderId: '831897287544',
    projectId: 'fitfam-c61fb',
    storageBucket: 'fitfam-c61fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSzRU-O1fheBeMzxXw5gz4iqURFA_697Q',
    appId: '1:831897287544:ios:289dbdd6b6af76127fe68d',
    messagingSenderId: '831897287544',
    projectId: 'fitfam-c61fb',
    storageBucket: 'fitfam-c61fb.firebasestorage.app',
    iosBundleId: 'com.example.dumbbellNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSzRU-O1fheBeMzxXw5gz4iqURFA_697Q',
    appId: '1:831897287544:ios:289dbdd6b6af76127fe68d',
    messagingSenderId: '831897287544',
    projectId: 'fitfam-c61fb',
    storageBucket: 'fitfam-c61fb.firebasestorage.app',
    iosBundleId: 'com.example.dumbbellNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEmH4kvdk9gC0YawUiJYZBSHCN1joZmlw',
    appId: '1:831897287544:web:6142d30cca5f844f7fe68d',
    messagingSenderId: '831897287544',
    projectId: 'fitfam-c61fb',
    authDomain: 'fitfam-c61fb.firebaseapp.com',
    storageBucket: 'fitfam-c61fb.firebasestorage.app',
    measurementId: 'G-N8PBZF5HRW',
  );
}
